### ISSUE TITLE
Improve font scaling

### ISSUE THREAD

**Issue by hbcoding** [WelterDevelopment/ConTeXt-IDE-WinUI#16]
TTo whom it may concern,
First, I would like to express a big thank you for creating this very promising context IDE. Having everything related to ConText in one place is great.
It would be great if the editor settings for font size management could be improved:
1)	Add a keyboard-short cut (CTRL+ “+”, CTRL + “-“ to increase / decrease font size. As setting are not preserved, it takes quite a few clicks to adjust font size on a 4K screen.
2)	Preserve the font size setting across multiple work sessions.
3)	Enable adding additional keyboard-short cuts for those functions in the Command palette not yet having short-cuts.
Thanks in advance for your help! HB

**Comment by WelterDevelopment** [comment]
Hi! You are welcome :)
Thanks for your feature proposal. I havent thought about high-res screens yet; still staying with 1080p... Are the Texts in the UI (Buttons, TreeViewItems, TabViewItemHeaders, ...) readable and do they scale with the pixel density? It would be helpfull if you would send a screenshot of the app with an open project so that I get a basic idea on how everything looks on a 4k screen.

To the actual proposal regarding the font size of the editor: 
- Workaround until the feature is implemented: To increase the font size of the monaco-editor very quickly, just use CTRL + MouseWheelUp

1. I will add the proposed short-cuts! If the short-cuts won't work (see 3.) I will create a "Font Size" option in the "Editor" ribbon tab
2. Yes, the font size will be two-way bound to a corresponding app setting (serialized in "settings.json")
3. The command pallete is kinda busted. Lots of command palette actions don't fire, even if I hit the corresponding short-cut (like "Toggle Line Comment"). Also, nothing happens, when I click on a context menu entry with the mouse. I am still investigating these issues and silently hoping that they will resolve with future releases of Project Reunion / WinUI 3 / WebView2 and MonacoEditorComponent (hawkerm/azchohfi)... 
Assigning own short-cuts to existing commands in the command palette "on-the-fly" is a good idea, I will add another setting for that. However, if the so set commands will actually fire is another story...

**Comment by WelterDevelopment** [comment]
1. and 2. now implemented, 3. moved to separate issue #17
